### ISSUE TITLE
Can not save image into Album

### ISSUE THREAD

**Issue by kokocooler2020** [rhymelph/r_album#1]
I was stetted READ&WRITE_EXTERNAL_STORAGE permissions in Manifest.xml, and granted those permissions in run time, and call RAlbum.createAlbum("album-name") already before to saving image,
But When Saving Image, I got this:
No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
at java.io.File.createNewFile(File.java:1008)
at com.rhyme.r_album.RAlbumPlugin$saveAlbum$1.invoke(RAlbumPlugin.kt:75)
at com.rhyme.r_album.RAlbumPlugin$saveAlbum$1.invoke(RAlbumPlugin.kt:25)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

I don't know why, any body help?

**Comment by kokocooler2020** [comment]
I founded reason, this plugin will find index of the char '.' in image file name, but my image file name not contains '.' char, it was named by MD5.

**Comment by rhymelph** [comment]
fix
